spring:
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /statics/**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 15
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      default-auto-commit: true
    wechat-db:
      username: xintijiao
      password: Zt1237890
    authcenter:
      username: xintijiao
      password: Zt1237890


  profiles:
        active: pro
  http:
    encoding:
      charset: utf-8

server:
  port: 804

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: me.myschools.xtjauthorizationcenter.domain

jwt:
  header: Authorization
  secret: "lua-resty-jwt"
  expiration: 5400
  tokenHead: "Bearer "

logging:
  config: classpath:logback-spring.xml

wechat:
  open:
    AppId: "wx8466bd57e3f3e42e"
    Secret: "ad4a573dc3bac78f77549c0d2abdf9b1"
  mini:
    AppId: "wx49cced01eec31847"
    Secret: "c2ef503983730e44d5c28568628ab57f"
  service:
    AppId: "wx3ac2549f640d5800"
    Secret: "1404accb33db71597e30ea688c718125"

---

spring:
  profiles: dev
  datasource:
    wechat-db:
      url: jdbc:mysql://120.26.44.61:13306/xtj-wechat?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    authcenter:
      url: jdbc:mysql://120.26.44.61:13306/xintijiao?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true

logback:
  logdir: E:\\LogFile\\xtj-authorizationcenter

---

spring:
  profiles: pro
  datasource:
    wechat-db:
      url: jdbc:mysql://rdsiqiqbzmajbrn.mysql.rds.aliyuncs.com:3306/xtj-wechat?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    authcenter:
      url: jdbc:mysql://rdsiqiqbzmajbrn.mysql.rds.aliyuncs.com:3306/xintijiao?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true

logback:
  logdir: /var/log/xtj-authorizationcenter-log/


