spring:
  mvc:
    throw-exception-if-no-handler-found: true
    static-path-pattern: /statics/**
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filters: stat
      driver-class-name: com.mysql.cj.jdbc.Driver
      initial-size: 1
      min-idle: 1
      max-active: 15
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
      default-auto-commit: true
      username: dev
      password: Zucc123456
  jackson:
    time-zone: GMT+8

  http:
    encoding:
      charset: utf-8

  profiles:
          active: dev

server:
  port: 808

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: tk.mybatis.springboot.model

mapper:
  mappers:
    - tk.mybatis.mapper.common.Mapper
    - tk.mybatis.mapper.common.Mapper2
  not-empty: true
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  offset-as-page-num: true
  row-bounds-with-count: true

logging:
  config: classpath:logback-spring.xml


---

spring:
  profiles: dev
  datasource:
    druid:
      url: jdbc:mysql://:3306/dev-xtjdisk?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai

logback:
  logdir: E:\LogFile\xtj-equipmentcenter\

---

spring:
  profiles: pro
  datasource:
      druid:
        url: jdbc:mysql://:3306/dev-xtjdisk?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=Asia/Shanghai

logback:
  logdir: /var/log/xtj-equipmentcenter-log/